package ai.blamely.actions

import ai.blamely.git.GitUtils
import com.intellij.notification.NotificationGroupManager
import com.intellij.notification.NotificationType
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.fileTypes.PlainTextFileType
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.testFramework.LightVirtualFile
import javax.swing.JOptionPane
import javax.swing.JPanel
import javax.swing.JTextField

/**
 * Shows a read-only `git show <sha>` summary for a session commit (or any SHA the user
 * pastes). Used by the **Blamely: Changes — Branch sessions** flow to inspect what was
 * captured in a closed session without leaving the IDE.
 */
class ShowSessionChangesAction : AnAction() {

    /** Action-class invocation: prompt the user for a SHA. */
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val sha = promptForSha(project) ?: return
        showFor(project, sha)
    }

    companion object {
        /** Programmatic entry point used by the Changes tool window when a session row is clicked. */
        fun showFor(project: Project, sha: String) {
            val repoRoot = GitUtils.getRepoRoot(project) ?: project.basePath ?: run {
                notify(project, "Not a git repository (could not resolve repo root)", NotificationType.ERROR)
                return
            }
            ApplicationManager.getApplication().executeOnPooledThread {
                val (code, stdout, stderr) = GitUtils.runWithStderr(
                    repoRoot,
                    "show",
                    "--stat",
                    "--patch",
                    "--no-color",
                    sha
                )
                ApplicationManager.getApplication().invokeLater {
                    if (project.isDisposed) return@invokeLater
                    if (code != 0 && stdout.isBlank()) {
                        notify(
                            project,
                            "git show ${sha.take(8)} failed: ${stderr.ifBlank { "exit=$code" }}",
                            NotificationType.WARNING
                        )
                        return@invokeLater
                    }
                    val header = buildString {
                        append("# git show ").append(sha).append('\n')
                        append("# repo: ").append(repoRoot).append('\n')
                        append("# (read-only summary generated by Blamely)\n\n")
                    }
                    val body = if (stdout.isBlank()) "(no diff output)\n" else stdout
                    val virtualFile = LightVirtualFile(
                        "git-show-${sha.take(8)}.diff",
                        PlainTextFileType.INSTANCE,
                        header + body
                    )
                    virtualFile.isWritable = false
                    FileEditorManager.getInstance(project).openFile(virtualFile, true)
                }
            }
        }

        private fun notify(project: Project, message: String, type: NotificationType) {
            NotificationGroupManager.getInstance().getNotificationGroup("Blamely")
                .createNotification(message, type)
                .notify(project)
        }
    }

    private fun promptForSha(project: Project): String? {
        val headSha = GitUtils.getLatestCommitSha(project)
        val field = JTextField(headSha ?: "", 42)
        val panel = JPanel().apply { add(field) }
        val ok = JOptionPane.showConfirmDialog(
            null,
            panel,
            "Blamely: Show changes for commit",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        ) == JOptionPane.OK_OPTION
        if (!ok) return null
        val sha = field.text.trim()
        if (sha.length < 7) {
            Messages.showWarningDialog(project, "Please enter a commit SHA (at least 7 characters)", "Blamely")
            return null
        }
        return sha
    }
}
